
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Jan 21 02:52:29 CET 2017
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 23;
  public static final int INCREMENT = 31;
  public static final int CONST = 8;
  public static final int RIGHTPAREN = 42;
  public static final int NOTEQUAL = 34;
  public static final int GREATER = 35;
  public static final int CONTINUE = 7;
  public static final int ASSIGNMOD = 29;
  public static final int SEMI_COMMA = 17;
  public static final int LESS = 37;
  public static final int FOR = 14;
  public static final int MINUS = 21;
  public static final int ASSIGNPLUS = 25;
  public static final int DECREMENT = 32;
  public static final int LEFTSQBRACKET = 43;
  public static final int LEFTPAREN = 41;
  public static final int STATIC = 16;
  public static final int LOGICALOR = 40;
  public static final int LESSEQUAL = 38;
  public static final int COMMA = 18;
  public static final int ASSIGNMINUS = 26;
  public static final int CLASS = 4;
  public static final int ASSIGNDIVIDE = 28;
  public static final int PLUS = 20;
  public static final int ASSIGN = 30;
  public static final int IF = 5;
  public static final int DOT = 19;
  public static final int LOGICALAND = 39;
  public static final int EOF = 0;
  public static final int RETURN = 12;
  public static final int EQUAL = 33;
  public static final int NEW = 9;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int NUMBER = 49;
  public static final int MOD = 24;
  public static final int IDENT = 47;
  public static final int BREAK = 3;
  public static final int VOID = 13;
  public static final int MULTIPLE = 22;
  public static final int GREATEREQUAL = 36;
  public static final int RIGHTBRACE = 46;
  public static final int ELSE = 6;
  public static final int READ = 11;
  public static final int KAPICA = 51;
  public static final int CHARCONST = 50;
  public static final int LEFTBRACE = 45;
  public static final int ASSIGNMULTIPLE = 27;
  public static final int BOOLCONST = 48;
  public static final int EXTENDS = 15;
  public static final int RIGHTSQBRACKET = 44;
  public static final int PRINT = 10;
}

